version: "3.9"


services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload && /app/start-reload.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:6.0
#    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
#    volumes:
#      - ./volumes/redis:/data
#      - ./redis.conf:/usr/local/etc/redis/redis.conf

  celery-worker:
    container_name: celer_worker
    restart: always
    build: .
    command: celery -A src.tasks.celery:celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    restart: always
    build: .
    command: celery -A src.tasks.celery:celery flower --port=5555
    ports:
      - "5556:5555"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
      - celery-worker
      - app